package cn.connxun.morui.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.connxun.morui.entity.Task_Allot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK__ALLOT".
*/
public class Task_AllotDao extends AbstractDao<Task_Allot, String> {

    public static final String TABLENAME = "TASK__ALLOT";

    /**
     * Properties of entity Task_Allot.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property DepartmentCode = new Property(3, String.class, "departmentCode", false, "DEPARTMENT_CODE");
        public final static Property DepartmentName = new Property(4, String.class, "departmentName", false, "DEPARTMENT_NAME");
        public final static Property JobsCode = new Property(5, String.class, "jobsCode", false, "JOBS_CODE");
        public final static Property JobsName = new Property(6, String.class, "jobsName", false, "JOBS_NAME");
        public final static Property PlanId = new Property(7, String.class, "planId", false, "PLAN_ID");
        public final static Property StartDate = new Property(8, String.class, "startDate", false, "START_DATE");
        public final static Property EndDate = new Property(9, String.class, "endDate", false, "END_DATE");
        public final static Property Type = new Property(10, int.class, "type", false, "TYPE");
        public final static Property Status = new Property(11, int.class, "status", false, "STATUS");
        public final static Property CheckUserEnterpriseId = new Property(12, int.class, "checkUserEnterpriseId", false, "CHECK_USER_ENTERPRISE_ID");
        public final static Property CheckUserDepartmentId = new Property(13, int.class, "checkUserDepartmentId", false, "CHECK_USER_DEPARTMENT_ID");
        public final static Property CheckUserJobsId = new Property(14, int.class, "checkUserJobsId", false, "CHECK_USER_JOBS_ID");
        public final static Property CheckUserId = new Property(15, int.class, "checkUserId", false, "CHECK_USER_ID");
        public final static Property CheckUserName = new Property(16, String.class, "checkUserName", false, "CHECK_USER_NAME");
        public final static Property TaskSubList = new Property(17, String.class, "taskSubList", false, "TASK_SUB_LIST");
        public final static Property UserId = new Property(18, long.class, "userId", false, "USER_ID");
    }


    public Task_AllotDao(DaoConfig config) {
        super(config);
    }
    
    public Task_AllotDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK__ALLOT\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"CONTENT\" TEXT," + // 2: content
                "\"DEPARTMENT_CODE\" TEXT," + // 3: departmentCode
                "\"DEPARTMENT_NAME\" TEXT," + // 4: departmentName
                "\"JOBS_CODE\" TEXT," + // 5: jobsCode
                "\"JOBS_NAME\" TEXT," + // 6: jobsName
                "\"PLAN_ID\" TEXT," + // 7: planId
                "\"START_DATE\" TEXT," + // 8: startDate
                "\"END_DATE\" TEXT," + // 9: endDate
                "\"TYPE\" INTEGER NOT NULL ," + // 10: type
                "\"STATUS\" INTEGER NOT NULL ," + // 11: status
                "\"CHECK_USER_ENTERPRISE_ID\" INTEGER NOT NULL ," + // 12: checkUserEnterpriseId
                "\"CHECK_USER_DEPARTMENT_ID\" INTEGER NOT NULL ," + // 13: checkUserDepartmentId
                "\"CHECK_USER_JOBS_ID\" INTEGER NOT NULL ," + // 14: checkUserJobsId
                "\"CHECK_USER_ID\" INTEGER NOT NULL ," + // 15: checkUserId
                "\"CHECK_USER_NAME\" TEXT," + // 16: checkUserName
                "\"TASK_SUB_LIST\" TEXT," + // 17: taskSubList
                "\"USER_ID\" INTEGER NOT NULL );"); // 18: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK__ALLOT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Task_Allot entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String departmentCode = entity.getDepartmentCode();
        if (departmentCode != null) {
            stmt.bindString(4, departmentCode);
        }
 
        String departmentName = entity.getDepartmentName();
        if (departmentName != null) {
            stmt.bindString(5, departmentName);
        }
 
        String jobsCode = entity.getJobsCode();
        if (jobsCode != null) {
            stmt.bindString(6, jobsCode);
        }
 
        String jobsName = entity.getJobsName();
        if (jobsName != null) {
            stmt.bindString(7, jobsName);
        }
 
        String planId = entity.getPlanId();
        if (planId != null) {
            stmt.bindString(8, planId);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(9, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(10, endDate);
        }
        stmt.bindLong(11, entity.getType());
        stmt.bindLong(12, entity.getStatus());
        stmt.bindLong(13, entity.getCheckUserEnterpriseId());
        stmt.bindLong(14, entity.getCheckUserDepartmentId());
        stmt.bindLong(15, entity.getCheckUserJobsId());
        stmt.bindLong(16, entity.getCheckUserId());
 
        String checkUserName = entity.getCheckUserName();
        if (checkUserName != null) {
            stmt.bindString(17, checkUserName);
        }
 
        String taskSubList = entity.getTaskSubList();
        if (taskSubList != null) {
            stmt.bindString(18, taskSubList);
        }
        stmt.bindLong(19, entity.getUserId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Task_Allot entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String departmentCode = entity.getDepartmentCode();
        if (departmentCode != null) {
            stmt.bindString(4, departmentCode);
        }
 
        String departmentName = entity.getDepartmentName();
        if (departmentName != null) {
            stmt.bindString(5, departmentName);
        }
 
        String jobsCode = entity.getJobsCode();
        if (jobsCode != null) {
            stmt.bindString(6, jobsCode);
        }
 
        String jobsName = entity.getJobsName();
        if (jobsName != null) {
            stmt.bindString(7, jobsName);
        }
 
        String planId = entity.getPlanId();
        if (planId != null) {
            stmt.bindString(8, planId);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(9, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(10, endDate);
        }
        stmt.bindLong(11, entity.getType());
        stmt.bindLong(12, entity.getStatus());
        stmt.bindLong(13, entity.getCheckUserEnterpriseId());
        stmt.bindLong(14, entity.getCheckUserDepartmentId());
        stmt.bindLong(15, entity.getCheckUserJobsId());
        stmt.bindLong(16, entity.getCheckUserId());
 
        String checkUserName = entity.getCheckUserName();
        if (checkUserName != null) {
            stmt.bindString(17, checkUserName);
        }
 
        String taskSubList = entity.getTaskSubList();
        if (taskSubList != null) {
            stmt.bindString(18, taskSubList);
        }
        stmt.bindLong(19, entity.getUserId());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Task_Allot readEntity(Cursor cursor, int offset) {
        Task_Allot entity = new Task_Allot( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // departmentCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // departmentName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // jobsCode
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // jobsName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // planId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // startDate
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // endDate
            cursor.getInt(offset + 10), // type
            cursor.getInt(offset + 11), // status
            cursor.getInt(offset + 12), // checkUserEnterpriseId
            cursor.getInt(offset + 13), // checkUserDepartmentId
            cursor.getInt(offset + 14), // checkUserJobsId
            cursor.getInt(offset + 15), // checkUserId
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // checkUserName
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // taskSubList
            cursor.getLong(offset + 18) // userId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Task_Allot entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDepartmentCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDepartmentName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setJobsCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setJobsName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPlanId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStartDate(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setEndDate(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setType(cursor.getInt(offset + 10));
        entity.setStatus(cursor.getInt(offset + 11));
        entity.setCheckUserEnterpriseId(cursor.getInt(offset + 12));
        entity.setCheckUserDepartmentId(cursor.getInt(offset + 13));
        entity.setCheckUserJobsId(cursor.getInt(offset + 14));
        entity.setCheckUserId(cursor.getInt(offset + 15));
        entity.setCheckUserName(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTaskSubList(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setUserId(cursor.getLong(offset + 18));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Task_Allot entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Task_Allot entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Task_Allot entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
